export const CHANGE_STATE = 'CHANGE_STATE';

export const REODER_QUESTIONS = 'REODER_QUESTIONS';
export const CHANGE_QUESTION = 'CHANGE_QUESTION';

export const STAGE_START = 'STAGE_START';
export const STAGE_PLAYING = 'STAGE_PLAYING';
export const STAGE_END = 'STAGE_END';
